# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0
site_name: "Wurzel"
site_url: https://github.com/telekom/wurzel

theme:
  name: readthedocs

plugins:
- search
- mkdocstrings



# Repository
repo_name: telekom/wurzel
repo_url: https://github.com/telekom/wurzel
