# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG (opensource@telekom.de)
#
# SPDX-License-Identifier: Apache-2.0
name: test.pypi.org Release
on:
  workflow_dispatch:


jobs:
  test-release:
    name: TestPyPI Release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    permissions: write-all


    environment:
      name: testpypi
      url: https://test.pypi.org/p/wurzel

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0


      - name: Setup | Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Generate version
        id: version
        run: |
          BASE_VERSION=$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'], end='')")
          VERSION="${BASE_VERSION}.dev.$(date +%Y%m%d%H%M%S)"
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Update version in pyproject.toml
        run: |
          sed -i "s/version = \".*\"/version = \"${{ steps.version.outputs.version }}\"/" pyproject.toml


      - name: Build package
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv build



      - name: Publish test ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
